stages:
  - test

variables:
  MYSQL_ROOT_PASSWORD: "$DATABASE_ROOT_PASSWORD"
  MYSQL_DATABASE: "$DATABASE"
  MYSQL_USER: "$DATABASE_USERNAME"
  MYSQL_PASSWORD: "$DATABASE_PASSWORD"

services:
  - name: mysql:8.0
    alias: db_ci

test:
  stage: test
  image: php:8.2.4-apache
  before_script:
    - apt-get update && apt-get install -y libzip-dev zip curl
    - docker-php-ext-install pdo_mysql zip
    - cp .env.cicd .env
    - echo $MYSQL_ROOT_PASSWORD"
    - echo $MYSQL_DATABASE"
    - echo $MYSQL_USER"
    - echo $MYSQL_PASSWORD"
    - apt-get update && apt-get install -y wget  # Install wget
    - wget -O composer-setup.php https://getcomposer.org/installer  # Download Composer installer
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer  # Install Composer
    - rm composer-setup.php  # Remove Composer setup file
    - composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader  # Install Composer dependencies
    - php artisan key:generate
  script:
    - php artisan test
  after_script:
    - rm .env  # Remove .env file after the tests
