stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: php:8.2.4-apache
  script:
    - phpunit --bootstrap vendor/autoload.php tests/Unit/UserControllerTest.php
    - phpunit --bootstrap vendor/autoload.php tests/Unit/AdminControllerTest.php
  allow_failure: false # Fail the pipeline if tests fail

build:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  dependencies:
    - test

deploy:
  stage: deploy
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:
    - docker pull $CI_REGISTRY_IMAGE
    - docker-compose -f docker-compose.yml up -d
  only:
    - master
  dependencies:
    - build