version: '3'

services:
    # Application Service
    thekre:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html

    # Database Service
    mysql:
        image: mysql:8.0
        container_name: mysql
        volumes:
            - ./data/thekre:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "thekre"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "root"

    # PhpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "9001:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306