version: '3'

services:
  # Application Service
  thekre:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thekre
    ports:
      - "3306:3306"


  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - "3307:3307"
    environment:
      - PMA_ARBITRARY=1
